Nodejs guides 4–6
werf/werf-guides pull request #318
Opened 2021-11-13 12:16 UTC by shvgn

Guides

  - 040 (db)
  - 050 (files w/minio)
  - 080 (config and secrets)
 
Unification and inheritance of the codebase

2021-11-13 12:22 UTC, shvgn commented on .werf/nginx-dev.conf
> +    #     charset utf-8;
- [ ] Not to forget to revert

2021-11-13 12:25 UTC, shvgn commented on docker-compose.yml
> +    restart: unless-stopped
- [ ] Not ot forget to revert

2021-11-17 12:25 UTC, Zhbert commented on _includes/ru/200_real_apps/040_db/nodejs/001_preparing_stateful_app.md.liquid
> +{{- "добавить бибилиотеки для работы с БД и подготовить для этого приложение" -}}
```suggestion
{{- "добавить библиотеки для работы с БД и подготовить для этого приложение." -}}
```

2021-11-17 12:42 UTC, Zhbert commented on _includes/ru/200_real_apps/040_db/nodejs/005_major_changes.md.liquid
> +1. Добавлена конфигцрация доступа к БД
```suggestion
1. Добавлена конфигурация доступа к БД
```

2021-11-17 12:43 UTC, Zhbert commented on _includes/ru/200_real_apps/040_db/nodejs/005_major_changes.md.liquid
> +Новые зависимости была установлены командой
```suggestion
Новые зависимости были установлены командой:
```

2021-11-17 13:29 UTC, Zhbert commented on _includes/ru/200_real_apps/040_db/nodejs/020_setup_db_work.md.liquid
> +Sequlize предполагает, что полкючения для всех окружений будут определены в одном файле. Пока что мы
```suggestion
Sequlize предполагает, что подключения для всех окружений будут определены в одном файле. Пока что мы
```

2021-11-17 13:51 UTC, Zhbert commented on _includes/ru/200_real_apps/050_s3/nodejs/001_preparing.md.liquid
> +  пригодится для отправки файлу клиенту
```suggestion
пригодится для отправки файлов клиенту
```

2021-11-17 13:57 UTC, Zhbert commented on _includes/ru/200_real_apps/080_configuration/nodejs/085_configs_including.md.liquid
> +Чтобы единообразно управлять конфигурацией приложения, уставновим модуль `config`:
```suggestion
Чтобы единообразно управлять конфигурацией приложения, установим модуль `config`:
```

2021-11-17 14:15 UTC, Zhbert requested changes
I found a couple of small typos

2021-11-17 14:21 UTC, Zhbert commented
I added layout:wip on page 040_db (we need to do something with the partial hierarchy later, where FIXME is marked)

2021-11-17 16:14 UTC, shvgn commented
Fixes applied

2021-11-17 16:19 UTC, Zhbert approved these changes

2021-11-17 22:41 UTC, merged